### ISSUE TITLE
How can set track change inside sample content box

### ISSUE THREAD

**Issue by Mariappan-KM** [ckeditor/ckeditor-docs-samples#15]
I want to insert a text with track changes inside the smaple box. but it does not allow me to add content with an ins tag. how can I do that?

**Comment by f1ames** [comment]
This is not a correct repository to report such tickets (here only issues regarding CKEditor 4 docs tutorials should be reported).

Simple Box is CKEditor 4 example widget while [track changes](https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/track-changes/track-changes.html) is CKEditor 5 feature and these two cannot be combined together.

**Comment by Mariappan-KM** [comment]
Thanks for your reply. I am talking about lite plugin[https://www.loopindex.com/lite/demo/](URL)

**Comment by f1ames** [comment]
LoopIndex Lite plugin is 3rd-party one so you should reach out to their support.
