### ISSUE TITLE
Uploadfile-config error

### ISSUE THREAD

**Issue by Nittarab** [ckeditor/ckeditor-docs-samples#5]
Hi, i tried to use Document Editor, it seems to work, but I get these errors:

[CKEDITOR] Error code: uploadfile-config.
(anonymous) @ ckeditor.js:19
[CKEDITOR] For more information about this error go to http://docs.ckeditor.com/#!/guide/dev_errors-section-uploadfile-config
(anonymous) @ ckeditor.js:19
 [CKEDITOR] Error code: uploadimage-config.
(anonymous) @ ckeditor.js:19
[CKEDITOR] For more information about this error go to http://docs.ckeditor.com/#!/guide/dev_errors-section-uploadimage-config

**Comment by f1ames** [comment]
Hello @Nittarab,
thank you for reporting. Have you checked the [docs link](http://docs.ckeditor.com/#!/guide/dev_errors-section-uploadfile-config) from the error message you posted?
In this case, these [config options](https://github.com/ckeditor/ckeditor-docs-samples/blob/master/editors/document-editor/index.html#L114) are not defined in this sample on purpose as they should point to the file manager / server handling files upload. You may read more on this topic in our offical docs: http://docs.ckeditor.com/#!/guide/dev_file_browse_upload and http://docs.ckeditor.com/#!/guide/dev_file_browser_api.
