### ISSUE TITLE
A4 page height 

### ISSUE THREAD

**Issue by Nittarab** [ckeditor/ckeditor-docs-samples#6]
Is possible to set the page height, and create a new page if is necessary?
So, can I use CKeditor to create document online?

**Comment by wwalc** [comment]
> Is possible to set the page height, and create a new page if is necessary?
Currently it is very hard / close to impossible in a reasonable period of time and ensuring a reasonable quality. And definitely not something available out of the box. The biggest challenge is with splitting complex structures, e.g. tables, nested lists when the content expands multiple pages and so on.

The "cheapest" way to offer some kind of page control would be to render a thumb preview of the document next to the edited page using e.g. wkhtmltopdf or PhantomJS. This way users would have at least some awareness of the number of pages and the way how the content is split.
